export const TRANSACTIONS_CATEGORIES = [
  'SUPERMARKET',
  'SUBSCRIPTION',
  'RENT',
  'SALARY',
  'GIFT',
  'EDUCATION',
  'HEALTH',
  'SHOPPING',
  'BILLS',
  'ENTERTAINMENT',
  'TRANSPORTATION',
  'PETS',
  'HOME',
  'SPORT',
  'UTILITIES',
  'ELECTRONICS',
  'INSURANCE',
  'CAR',
  'FRIENDS',
  'OTHER',
];

export const TRANSACTIONS_TYPES = ['INCOME', 'EXPENSE'];

export const TRANSACTIONS_PAYMENT_METHODS = ['CASH', 'CREDIT-CARD', 'TRANSFER', 'OTHER'];
